2019-07-06 15:19:31,981 INFO: Microblog startup [in /Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/app/__init__.py:45]
2019-07-06 15:20:11,767 ERROR: Exception on /edit_profile [POST] [in /Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: authuser.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/app/routes.py", line 90, in edit_profile
    db.session.commit()
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 494, in commit
    self._prepare_impl()
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 473, in _prepare_impl
    self.session.flush()
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2459, in flush
    self._flush(objects)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 154, in reraise
    raise value
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2557, in _flush
    flush_context.execute()
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    update,
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 996, in _emit_update_statements
    statement, multiparams
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 399, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value.with_traceback(tb)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: authuser.username
[SQL: UPDATE authuser SET username=?, last_seen=? WHERE authuser.id = ?]
[parameters: ('momo', '2019-07-06 22:20:11.766014', 3)]
(Background on this error at: http://sqlalche.me/e/gkpj)
