2019-07-09 05:25:01,565 ERROR: Exception on / [GET] [in /Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/app/routes.py", line 30, in index
    return render_template('index.html', title='Home', user=user, posts=posts)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/app/templates/base.html", line 16, in top-level template code
    <a href="{{ url_for('/registercouple') }}">Couple Registration</a>
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py", line 2080, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/werkzeug/routing.py", line 2007, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint '/registercouple'. Did you mean 'registercouple' instead?
2019-07-09 05:25:30,455 INFO: Microblog startup [in /Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/app/__init__.py:45]
2019-07-09 05:25:38,130 ERROR: Exception on /registercouple [GET] [in /Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/app/routes.py", line 75, in registercouple
    form = CoupleForm()
NameError: name 'CoupleForm' is not defined
2019-07-09 05:27:17,874 INFO: Microblog startup [in /Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/app/__init__.py:45]
2019-07-09 05:27:24,865 ERROR: Exception on /registercouple [GET] [in /Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/venv/lib/python3.6/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/app/routes.py", line 75, in registercouple
    form = CoupleForm()
NameError: name 'CoupleForm' is not defined
2019-07-09 05:33:37,025 INFO: Microblog startup [in /Users/jeffelcapitan/Desktop/_python_tutorials/june2019grinbergchapel/flaskchapel/app/__init__.py:45]
